HOSTS:
  el7-server:
    roles:
      - default
      - master
      - client
      - server
    platform: el-7-x86_64
    box: puppetlabs/centos-7.2-64-nocm 
    hypervisor: vagrant
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/mirrorlist?repo=epel-6&arch=$basearch&country=us'
        gpgkeys:
          - https://getfedora.org/static/0608B895.txt
CONFIG:
  log_level: verbose
  type: foss
  vagrant_memsize: 512
