Vagrant.configure("2") do |c|
  c.ssh.insert_key = false
  c.vm.define 'el6-server' do |v|
    v.vm.hostname = 'el6-server'
    v.vm.box = 'puppetlabs/centos-7.2-64-nocm'
    v.vm.box_check_update = 'true'
    v.vm.network :private_network, ip: "10.255.198.88", :netmask => "255.255.0.0", :mac => "08002776F365"
    v.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '512', '--cpus', '1']
    end
  end
end
